### ISSUE TITLE
get killed in robbery and hunting

### ISSUE THREAD

**Issue by Koles1910** [grimaldello/the-crims-italian-bot-v2#65]
I would introduce your mode to get killed in robberies and hunts by id or name, as everyone knows if you run away in the hunt people with top then they report and start checking us, so it would be added id such top so that they can kill us and not report it us, in the worst case, the id of the admins would be added so that if they checked us and wanted to kill us, they could do it, it may be that we add the id or name and if the bot detects them in the club, it will slow down the movement of the fake mouse and if it does not detect it, it will run normally this may eliminate the check

**Comment by grimaldello** [comment]
Hi, not so simple to add this this functionality.

However, a similar result can be achieved by using the "Wait to be killed" functionality added some time ago.

If you suspect that you are about to be reported, because you escape too fast from admin or pro-hunters, you run the bot with "Wait to be killed" functionality and put the usernames/ids of the admins/pro-hunters that you want to permit to kill (and obviously escape for all others).
