### ISSUE TITLE
Robbery button bug

### ISSUE THREAD

**Issue by Fatalitly** [grimaldello/the-crims-italian-bot-v2#71]
The problem I will talk about now is not a bot, but a problem with the game itself. 
Maybe you can come up with a solution for this. When we click on the robbery button at regular intervals while doing the robbery, the screen below is stuck on a blank screen as it is. And the page needs to be refreshed. However, this is how it works. When this problem happens, it naturally pauses on the bot and does not continue. If the bot periodically refreshes the page, I think we will get rid of this problem. 

![deneme](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/83348930/9bb9c770-83c4-4998-a9ac-ff9f5e1a7783)

**Comment by grimaldello** [comment]
Hi @Fatalitly,

thank you for reporting the issue.

This issue was already reported in the past: https://github.com/grimaldello/the-crims-italian-bot-v2/issues/52

Unfortunately at the moment I don't know how to implement a "real" solution.
I could implement an automatic refresh, but the bot will stop working, because by reloading the page the Javascript code of the bot must be pasted again in the browser console.
Maybe there's a solution by using browser extensions but I don't want that the the bot depends on external tool (but you are free to do it if you are able to do that.

As wrote in the previous issue reported, it seems that as a workaround for the problem (or to minimize it) you have to:

- Not use random rave:

```js
rechargeEnergy: {
                useRandomRaveForRecharge: false,
...
}
```

- Increment wait time after exit rave:
```
millisecondsToWaitAfterExitRave: {
min: 600,
max: 1000,
},
millisecondsToWaitAfterClickExitButton: {
min: 600,
max: 1000,
},
```
