### ISSUE TITLE
account under investigation = bot running slowly

### ISSUE THREAD

**Issue by alexandereis** [grimaldello/the-crims-italian-bot-v2#79]
When the account is under investigation, the bot's movements are very slow, making it impossible to want to continue using it even knowing about the investigation. Wouldn't it be possible to remove that? I would like to continue using the bot, but keeping the same configured speed

**Comment by grimaldello** [comment]
Unfortunately this is a limitation of the bot, due to the Javascript tha is single threaded (this is my guess).

I explained it here: https://github.com/grimaldello/the-crims-italian-bot-v2#bot-speed

Basically you need to set a higher value for:

```
mouse: {
    numberOfCoordinatesToSkip: XXX
},
```

Increment it step by step until you find the desired speed.

**Comment by alexandereis** [comment]
I followed your comment on discord, perfect, I'll analyze it here

**Comment by alexandereis** [comment]
I followed your comment on discord, perfect, I'll analyze it here
